# Generated by Django 4.1 on 2022-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=200)),
                ('lead_addr', models.CharField(max_length=200)),
                ('lead_descript', models.TextField()),
                ('lead_received', models.DateTimeField(verbose_name='Date Received')),
            ],
        ),
    ]
